export type Pillar = "cognitive" | "language" | "physical" | "socialEmotional" | "creative";

export type ActivityPhase = "explorer" | "communicator" | "builder";

export interface MontessoriActivity {
  id: string;
  title: string;
  subtitle: string;
  duration: string;
  pillars: Pillar[];
  phase: ActivityPhase;
  ageRange: string;
  materials: string[];
  steps: string[];
  montessoriPrinciple: string;
  brainBenefit: string;
  rightBrainFocus: string;
  tipForParent: string;
  category: "sensory" | "motor" | "language" | "creative" | "cognitive" | "outdoor";
  difficulty: "gentle" | "moderate" | "engaging";
}

export const ACTIVITIES: MontessoriActivity[] = [
  {
    id: "masala-tray",
    title: "The Masala Tray",
    subtitle: "Olfactory exploration with Indian spices",
    duration: "10–15 min",
    pillars: ["cognitive", "creative", "language"],
    phase: "explorer",
    ageRange: "16–20 months",
    materials: ["Cinnamon sticks", "Cardamom pods (elaichi)", "Fennel seeds (saunf)", "Star anise", "Small steel katoris"],
    steps: [
      "Lay out each spice in its own steel katori on a tray at child's height.",
      "Sit together and pick up each spice slowly. Say its name: 'This is cinnamon — dalchini.' Inhale deeply together.",
      "Let her touch, smell, and explore each one at her own pace. Do not rush.",
      "After smelling, invite her to place each katori back. This teaches order and completion.",
      "Name the sensation: 'Does it smell sweet? Warm? Spicy?' Build olfactory vocabulary.",
    ],
    montessoriPrinciple: "Isolation of Stimuli — focusing one sense at a time builds neural pathways for deep sensory processing.",
    brainBenefit: "Activates the olfactory bulb which is directly linked to memory and emotional centers. Builds rich sensory vocabulary and cross-modal brain connections.",
    rightBrainFocus: "Holistic sensory integration — the right brain processes emotional memory and sensory experience simultaneously. Olfactory stimulation is one of the most direct routes to right-brain activation.",
    tipForParent: "Wait 30 seconds before naming anything. Let her brain process the scent first. The pause is where the neural work happens.",
    category: "sensory",
    difficulty: "gentle",
  },
  {
    id: "steel-dabba-nesting",
    title: "Steel Dabba & Donia Mastery",
    subtitle: "Spatial reasoning with kitchen vessels",
    duration: "15–20 min",
    pillars: ["cognitive", "physical"],
    phase: "explorer",
    ageRange: "16–20 months",
    materials: ["4–6 steel tiffin boxes (dabbas) of different sizes", "3–4 small steel bowls (donias)", "A low table or mat"],
    steps: [
      "Arrange all vessels randomly on the mat. Sit across from her and observe.",
      "Let her experiment freely. She may try to nest, stack, or bang — all are valid explorations.",
      "When she struggles, count to 30 silently before offering the gentlest hint: 'Which one is bigger?'",
      "Name what she discovers: 'You put the small one inside the big one. Inside! Andar!'",
      "After 15 minutes, slow the pace. Invite her to put each piece away one by one.",
    ],
    montessoriPrinciple: "The 'Fill and Spill' principle — children learn volume, containment, and physics through hands-on repetition, not instruction.",
    brainBenefit: "Builds spatial reasoning, volume understanding, and the physics of 'fit'. The auditory feedback of steel on steel provides cross-sensory reinforcement.",
    rightBrainFocus: "Spatial intelligence is primarily right-brained. Nesting activates three-dimensional spatial processing, a foundational skill for creativity, engineering, and mathematical intuition.",
    tipForParent: "Resist showing her 'how'. The moment of figure-it-out is the learning. Your patience is her greatest gift.",
    category: "cognitive",
    difficulty: "gentle",
  },
  {
    id: "atta-dough-play",
    title: "Atta Dough Sculpting",
    subtitle: "Whole wheat playdough for hand strength",
    duration: "20–30 min",
    pillars: ["creative", "physical", "cognitive"],
    phase: "explorer",
    ageRange: "16–22 months",
    materials: ["1 cup whole wheat flour (atta)", "Water", "Pinch of salt", "Optional: turmeric for colour", "A low mat or tray"],
    steps: [
      "Make dough together: pour flour, let her touch it, then add water slowly. Name the transformation: 'Look — it becomes one!'",
      "Start with the simplest gesture: squeeze. Let her just squeeze. Do not direct.",
      "Introduce rolling slowly with your palm. She will imitate.",
      "Tear a piece for her to poke with one finger. 'Poke! Chubhao!' This builds precise motor control.",
      "Let her make anything or nothing. Process over product — every time.",
    ],
    montessoriPrinciple: "Process-based creation — the act of making, not the result, is what builds the brain. Children who 'play' with dough are doing serious developmental work.",
    brainBenefit: "Builds intrinsic hand strength critical for writing. Activates proprioceptive receptors in the hands that are directly linked to cognitive development.",
    rightBrainFocus: "Three-dimensional spatial creativity, tactile imagination, and the integration of touch with creative intention — all right-brain dominant functions.",
    tipForParent: "Never ask 'What is it?' — this implies there should be a correct answer. Ask instead: 'Tell me about what you made.' Or say nothing at all.",
    category: "creative",
    difficulty: "gentle",
  },
  {
    id: "mirror-body-map",
    title: "Mirror Body Map",
    subtitle: "Identity and language through reflection",
    duration: "10–15 min",
    pillars: ["language", "socialEmotional", "cognitive"],
    phase: "explorer",
    ageRange: "16–20 months",
    materials: ["A full-length mirror or large wall mirror", "Optional: small dot stickers in different colours"],
    steps: [
      "Sit together in front of the mirror. Let her stare — self-recognition is still new and magical.",
      "Begin slowly: 'Naak' (touch her nose in the mirror), then 'Nose'. Always mother tongue first.",
      "Wait. Does she touch her own nose? If yes, celebrate with a soft 'Yes! Naak!'",
      "Move through: eyes (aankh), ears (kaan), mouth (mooh), hair (baal), hands (haath).",
      "Optional: stick a small coloured dot on her hand. Watch her find it in the mirror — a beautiful moment of spatial self-awareness.",
    ],
    montessoriPrinciple: "Mirror neurons and self-schema — the child is building a mental map of herself as a separate, capable being. This is foundational for identity and empathy.",
    brainBenefit: "Activates the self-processing network and builds body schema. Trilingual naming builds parallel neural pathways for three languages simultaneously.",
    rightBrainFocus: "The right hemisphere is dominant for face recognition, spatial self-awareness, and emotional self-perception — this activity targets all three in one elegant session.",
    tipForParent: "Do not rush to the next body part. Her pause is processing. If she points to your nose instead of hers, that is a beautiful sign of empathy — she is including you.",
    category: "language",
    difficulty: "gentle",
  },
  {
    id: "water-pour-science",
    title: "The Pouring Lab",
    subtitle: "Water mathematics on the balcony",
    duration: "20–25 min",
    pillars: ["cognitive", "physical", "creative"],
    phase: "explorer",
    ageRange: "16–24 months",
    materials: ["Small plastic tub or bucket (half-filled with water)", "2–3 steel cups of different sizes", "A mug", "Old towel or outdoor space"],
    steps: [
      "Set up the water station outdoors or in the bath. Dress her for mess.",
      "Begin by pouring slowly yourself. Say nothing. Let her watch the arc of water.",
      "Hand her a full cup. Do not guide. She will pour — possibly everywhere. Celebrate.",
      "Introduce vocabulary: 'Full — bhari. Empty — khali. Pour — dalo.'",
      "After several rounds, try: 'Can you pour from the big cup into the small one? Will it all fit?'",
    ],
    montessoriPrinciple: "Concrete volume mathematics — before a child can understand '2 cups equals 1 jug', she must feel it with water, again and again. Abstract thinking builds from concrete experience.",
    brainBenefit: "Develops volume conservation (a Piagetian milestone), fine motor control, and visual tracking. Water play is deeply regulating for the nervous system.",
    rightBrainFocus: "Fluid, non-linear thinking — the right brain processes holistic patterns like 'the water becomes the cup's shape'. This is spatial and creative cognition at its most fundamental.",
    tipForParent: "Resist labelling what is 'correct'. If she pours it all out immediately, she is testing the physics of emptying. That is perfect science.",
    category: "sensory",
    difficulty: "gentle",
  },
  {
    id: "sabzi-mandi-lab",
    title: "The Sabzi Mandi Lab",
    subtitle: "Real-world multilingual sensory exploration",
    duration: "45–60 min outing",
    pillars: ["language", "cognitive", "socialEmotional"],
    phase: "explorer",
    ageRange: "16–28 months",
    materials: ["A visit to your local vegetable market", "Small cloth bag she can carry", "No screens"],
    steps: [
      "Let her walk as much as possible — the uneven surfaces of a market floor are vestibular training.",
      "Stop at each stall. Name slowly: 'Tomato... Tamatar... Laal (Red)'. Give her three words at once.",
      "Let her touch: the smooth skin of a brinjal, the rough surface of a gourd, the feathery top of fennel.",
      "Watch her eyes. Where does she track? Follow her gaze and name what she sees.",
      "Buy one vegetable together. Let her hold it in her bag the whole way home — ownership builds pride.",
    ],
    montessoriPrinciple: "Real-world learning environments are irreplaceable. The Montessori principle of the 'prepared environment' extends to the real world — a market is a living curriculum.",
    brainBenefit: "Simultaneous visual, tactile, auditory, and olfactory stimulation creates multi-sensory memories that are retained far more effectively than single-sense experiences.",
    rightBrainFocus: "The right brain integrates multisensory information into holistic understanding. The market provides natural complexity that no toy can replicate.",
    tipForParent: "Use the market as a language lab, not a task. If she wants to stare at the scale for 5 minutes, let her. She is studying cause-and-effect physics.",
    category: "outdoor",
    difficulty: "moderate",
  },
  {
    id: "emotion-face-cards",
    title: "Emotion Face Cards",
    subtitle: "Building emotional vocabulary and empathy",
    duration: "10–15 min",
    pillars: ["socialEmotional", "language", "creative"],
    phase: "communicator",
    ageRange: "17–24 months",
    materials: ["4–6 paper cards", "Thick markers", "Optional: printed emotion photos"],
    steps: [
      "Draw simple faces: happy (khush), sad (udaas), surprised (hairaan), tired (thaka hua). Keep them large and clear.",
      "Hold up the 'happy' card. Make the face yourself. Ask: 'Kaisi feeling hai?' (How is she feeling?)",
      "Let her point to the card that matches her current feeling. Do not correct — validate.",
      "After a few rounds, reflect your own emotion: 'Mama is feeling tired today. Thaki hoon.'",
      "Close with a warm hug. Emotional learning is never purely cognitive — it must be felt.",
    ],
    montessoriPrinciple: "Emotional vocabulary precedes emotional regulation. A child who can name her feeling is 40% more likely to be able to manage it — this is core Montessori social-emotional work.",
    brainBenefit: "Builds the emotional vocabulary network in the prefrontal cortex while simultaneously activating the amygdala. This integration is the basis of emotional intelligence.",
    rightBrainFocus: "Emotional processing, face recognition, and social intuition are all right-brain dominant. Naming emotions bridges right-brain feeling with left-brain language — a critical developmental integration.",
    tipForParent: "Never say 'Don't be sad' or 'Don't cry'. Instead: 'You are feeling sad. That makes sense. I am here.' Validation precedes regulation.",
    category: "cognitive",
    difficulty: "gentle",
  },
  {
    id: "threading-beads",
    title: "Bead Threading",
    subtitle: "Fine motor mastery for future writing",
    duration: "15–20 min",
    pillars: ["physical", "cognitive", "creative"],
    phase: "communicator",
    ageRange: "18–24 months",
    materials: ["Large wooden beads (min 2cm diameter)", "Thick shoelace or blunt-tipped cord", "A small bowl to hold beads"],
    steps: [
      "Lay out 6–8 beads in a bowl. Show her the end of the lace.",
      "Thread one bead slowly in front of her. Say: 'Thread. Dhaago mein daalo.' Then place it in her hands.",
      "The first attempt may fail many times. This is the point. Count silently to 30 before helping.",
      "When she threads one, pause. Let her feel the satisfaction before the praise.",
      "After 3–4 beads, she may lose interest. Stop before frustration. End on a success.",
    ],
    montessoriPrinciple: "The pincer grasp — the ability to pick up small objects with two fingers — is the direct precursor to handwriting. Bead threading is the gold standard Montessori preparation for writing.",
    brainBenefit: "Activates the hand-brain connection, builds bilateral coordination, and develops the focused attention span required for complex tasks.",
    rightBrainFocus: "Sequential fine motor tasks activate coordination between both hemispheres. The creative satisfaction of making a 'necklace' engages right-brain reward pathways that reinforce the activity.",
    tipForParent: "Use the bead colours as a language opportunity: 'Red bead. Laal manka. Now orange — santra rang.' Make it a bilingual counting meditation.",
    category: "motor",
    difficulty: "moderate",
  },
  {
    id: "laundry-maximum-effort",
    title: "The Laundry Helper",
    subtitle: "Maximum Effort — carrying, pushing, working",
    duration: "10–15 min",
    pillars: ["physical", "socialEmotional", "cognitive"],
    phase: "explorer",
    ageRange: "16–20 months",
    materials: ["A laundry basket (lightly filled so it's heavy but manageable)", "Clean, folded clothes"],
    steps: [
      "Bring the laundry basket to her level. 'Can you push this to the bedroom?'",
      "Do not lift it for her. Let her feel the weight and figure out how to push.",
      "As she pushes, narrate: 'You are so strong! You are helping Mama!'",
      "Let her 'help' place clothes — even messily. Fold nothing. The point is participation.",
      "End with a genuine thank you: 'Thank you for helping. Shukriya.' This builds a sense of meaningful contribution.",
    ],
    montessoriPrinciple: "Maximum Effort — toddlers have an internal drive to use their full physical capacity. Carrying, pushing, and lifting heavy objects satisfies this need and builds physical confidence and community belonging.",
    brainBenefit: "Proprioceptive input from heavy work regulates the nervous system. Children who do 'heavy work' daily are calmer, more focused, and have better self-regulation.",
    rightBrainFocus: "The right brain governs spatial navigation, body awareness in space, and the emotional sense of belonging — all activated when a child does meaningful real-world work.",
    tipForParent: "The mess does not matter. The feeling of 'I helped' is building her brain and her sense of self as a capable, contributing member of this family.",
    category: "motor",
    difficulty: "moderate",
  },
  {
    id: "obstacle-course",
    title: "The Living Room Obstacle Course",
    subtitle: "Vestibular adventure with pillows and cushions",
    duration: "20–30 min",
    pillars: ["physical", "cognitive", "socialEmotional"],
    phase: "explorer",
    ageRange: "16–20 months",
    materials: ["Bolsters", "Floor cushions", "Rolled mattress", "Sofa pillows"],
    steps: [
      "Create a path: crawl through a bolster tunnel, climb over a cushion mountain, walk along a mattress 'bridge'.",
      "Demonstrate once, slowly. Then say: 'Your turn! Tumhari baari!'",
      "Resist the urge to hold her hands. Let her find her own balance.",
      "Cheer discovery, not just success: 'You are figuring it out!'",
      "After several rounds, change one element. Novelty forces the brain to re-calculate — this is the learning.",
    ],
    montessoriPrinciple: "Vestibular stimulation is foundational for all learning. The inner ear system (balance) is directly connected to attention, emotional regulation, and reading readiness.",
    brainBenefit: "Builds gross motor coordination, spatial navigation, and risk assessment. Physical challenge in a safe environment builds neural resilience.",
    rightBrainFocus: "Spatial-kinesthetic intelligence is right-brain dominant. The challenge of novel physical paths builds the right brain's ability to process three-dimensional space intuitively.",
    tipForParent: "Do not remove obstacles that make her nervous. Stay close, but let her pause at the edge of her comfort zone. That pause is courage being built.",
    category: "motor",
    difficulty: "engaging",
  },
  {
    id: "pretend-play-kitchen",
    title: "The Pretend Kitchen",
    subtitle: "Symbolic play for cognitive leap",
    duration: "20–30 min",
    pillars: ["creative", "language", "socialEmotional"],
    phase: "communicator",
    ageRange: "17–24 months",
    materials: ["A doll or teddy", "Small steel pots or plastic containers", "Wooden spoon", "Bits of soft food she can pretend to stir"],
    steps: [
      "Set up a 'kitchen corner' at floor level. Place the doll in a chair.",
      "Start cooking yourself — stir dramatically. 'I am making khichdi for doll. Dal daalo!'",
      "Invite her to help: 'Can you stir the dal?' Hand her the spoon.",
      "Feed the doll together. 'Doll is hungry. Bhook lagi hai.' Let her feed it.",
      "Extend: 'Is doll happy now? Khush hai?' Ask about the doll's experience, not just the action.",
    ],
    montessoriPrinciple: "Symbolic/pretend play is the highest cognitive achievement of toddlerhood. When a child uses a stick as a spoon, she is performing an act of abstraction — the foundation of all symbolic thought including language and mathematics.",
    brainBenefit: "Activates the prefrontal cortex (planning), Broca's area (language), and the mirror neuron system (empathy) simultaneously — the most cognitively rich single activity for this age.",
    rightBrainFocus: "Narrative imagination, empathy, and symbolic thinking are right-brain functions. Pretend play is the right brain's native language — it is how the non-verbal, emotional hemisphere thinks.",
    tipForParent: "Let her scripts be chaotic. If she decides to make the doll fly instead of eat, follow her lead. Creative divergence is intelligence in its rawest form.",
    category: "creative",
    difficulty: "moderate",
  },
  {
    id: "colour-sorting",
    title: "Colour Sorting with Bangles",
    subtitle: "Categorisation and early logic",
    duration: "15–20 min",
    pillars: ["cognitive", "physical", "language"],
    phase: "communicator",
    ageRange: "20–24 months",
    materials: ["Coloured bangles or bottle caps (4–6 of each of 2 colours)", "2 small bowls or katoris"],
    steps: [
      "Mix all items together in a pile. Place 2 empty bowls beside it.",
      "Put one red bangle in one bowl, one blue in the other. Say nothing else.",
      "Let her observe. She may try to sort. She may not. Both are fine.",
      "If she places incorrectly, do not correct. Say: 'Hmm, what colour is this?' Pause. 'Laal? Red?'",
      "When the sort is complete, celebrate the work, not the accuracy: 'You sorted everything! Sab alag kiya!'",
    ],
    montessoriPrinciple: "Do not correct wrong placements — let the child self-discover through repetition. The goal is building the concept of 'category', not memorising colour names.",
    brainBenefit: "Categorisation is the foundation of all human reasoning. Building the mental schema of 'things that go together' is the basis of mathematics, language, and scientific thinking.",
    rightBrainFocus: "The right brain sees patterns holistically before the left brain can articulate rules. Colour sorting gives the right brain a concrete pattern task — the left brain labels it later.",
    tipForParent: "Do this same activity for two weeks before changing the colours. Repetition is not boredom for a toddler — it is mastery in progress.",
    category: "cognitive",
    difficulty: "moderate",
  },
  {
    id: "handprint-art",
    title: "Handprint Painting",
    subtitle: "Process art and identity celebration",
    duration: "20–30 min",
    pillars: ["creative", "physical", "socialEmotional"],
    phase: "communicator",
    ageRange: "18–24 months",
    materials: ["Food-safe paint: turmeric (yellow), beetroot juice (pink), spinach water (green)", "Large sheet of paper", "Old clothes"],
    steps: [
      "Mix colours with water to a safe, thin consistency. No brushes yet — use fingers.",
      "Dip your own hand first. Make a print. Let her observe.",
      "Invite her to press her palm into the colour. Guide it to the paper together.",
      "Say: 'Your hand! Tera haath!' Let her see her own impression on the world.",
      "Display the art immediately on the fridge. Her work must be seen, honoured, and permanent.",
    ],
    montessoriPrinciple: "Process art — never ask what she painted. The physical act of applying colour to surface, the surprise of the handprint, is the entire curriculum.",
    brainBenefit: "Multi-sensory tactile-visual-motor activity that simultaneously builds hand-eye coordination, colour processing, and the crucial sense of 'I made this — I affect the world.'",
    rightBrainFocus: "Visual-spatial creativity, whole-body sensory experience, and emotional self-expression are quintessentially right-brain. The handprint is a child's first signature — her right brain's declaration of existence.",
    tipForParent: "Keep the final artwork, even if it looks like a chaos of colour. In 10 years, it will be the most precious object in your home.",
    category: "creative",
    difficulty: "gentle",
  },
  {
    id: "nature-treasure-walk",
    title: "Nature Treasure Walk",
    subtitle: "Collecting, naming, and classifying outdoors",
    duration: "30–45 min",
    pillars: ["cognitive", "language", "physical"],
    phase: "communicator",
    ageRange: "19–26 months",
    materials: ["A small cloth bag or basket", "The outdoors", "Optional: a simple scrapbook for later"],
    steps: [
      "Give her the bag before leaving. 'Today we look for treasures. Khazana dhundhte hain!'",
      "Let her lead the walk. Follow her gaze and her pace — do not set a destination.",
      "When she picks something up: 'A leaf! Patta! It is green — Hara. Rough? Smooth?'",
      "Collect whatever she chooses: stones, sticks, flowers, feathers. All are valid.",
      "At home, lay out the collection. Sort together if she wishes — or simply look and name.",
    ],
    montessoriPrinciple: "Nature provides what no classroom can — spontaneous curiosity. A child-led nature walk teaches the scientific method: observe, collect, classify, reflect.",
    brainBenefit: "Outdoor 'green time' reduces cortisol, improves attention, and stimulates curiosity circuits. Child-led exploration builds intrinsic motivation and executive function.",
    rightBrainFocus: "The right brain is the navigator — it builds holistic spatial maps of real environments. Nature walks build this spatial intelligence while simultaneously stimulating right-brain sensory integration.",
    tipForParent: "Resist the impulse to name everything before she does. Her pointing finger is a question — answer it, but only after a 3-second pause for her brain to process.",
    category: "outdoor",
    difficulty: "gentle",
  },
  {
    id: "puppet-storytelling",
    title: "Puppet Story Theatre",
    subtitle: "Language through imagination and play",
    duration: "15–20 min",
    pillars: ["language", "creative", "socialEmotional"],
    phase: "builder",
    ageRange: "22–28 months",
    materials: ["A sock puppet or any soft toy held behind a surface", "A simple 'stage' (table edge or sofa back)"],
    steps: [
      "Introduce the puppet: 'This is Raju. Raju loves mangoes.' Give the puppet a simple personality.",
      "Start a story: 'Raju went to the garden... and found something.' Pause. 'What did Raju find?'",
      "Let her fill the gaps. Accept any answer as part of the story.",
      "Let her hold the puppet and give it a voice — even if it is just sounds.",
      "End with a resolution: 'Raju is tired now. Time to sleep. Good night, Raju.'",
    ],
    montessoriPrinciple: "Children speak more freely to and through puppets than directly to adults. Puppet play lowers the 'performance anxiety' of language, allowing vocabulary to emerge naturally.",
    brainBenefit: "Narrative construction activates the prefrontal cortex, Broca's area, and emotional processing regions simultaneously — the most complex language task of toddlerhood.",
    rightBrainFocus: "Character imagination, story-sense, and emotional narrative are all right-brain domain. The child who invents a story for a puppet is doing advanced right-brain work that will later power creative writing, empathy, and leadership.",
    tipForParent: "The story does not need to make sense. If she says 'Raju flew to the moon', follow that plot twist. Your willingness to be surprised is her invitation to be bold.",
    category: "language",
    difficulty: "moderate",
  },
  {
    id: "shape-sorter-challenges",
    title: "Shape Sorter Challenge",
    subtitle: "Spatial problem-solving and visual discrimination",
    duration: "10–15 min",
    pillars: ["cognitive", "physical"],
    phase: "builder",
    ageRange: "22–28 months",
    materials: ["A 3–5 shape wooden sorter", "Optional: extend with household items — round cups, square boxes"],
    steps: [
      "Place the sorter on a low surface. Set the shapes beside it.",
      "Let her attempt each shape herself. Do not guide her hand.",
      "If she is frustrated: 'It does not fit this way. Can we turn it?' — a question, not a solution.",
      "Name each shape: 'Circle — gol. Square — varg.' Keep it trilingual.",
      "After mastery, challenge: 'Which one do you think will fit here?' Build prediction thinking.",
    ],
    montessoriPrinciple: "The 30-second rule — before intervening, always wait. The moment just before success is the moment of maximum brain growth.",
    brainBenefit: "Visual-spatial discrimination, hand-eye coordination, and problem-solving persistence are built through this single activity when done without over-helping.",
    rightBrainFocus: "Spatial rotation and form perception are right-brain dominant. The 'aha' moment of fitting a shape is a right-brain breakthrough that produces genuine dopamine — building the love of problem-solving.",
    tipForParent: "When she succeeds, pause before cheering. Let her feel her own competence for 2–3 seconds before you celebrate. That pause builds intrinsic motivation.",
    category: "cognitive",
    difficulty: "engaging",
  },
];

export const MILESTONES = [
  {
    id: "m16",
    age: "16 months",
    month: 16,
    physical: ["Walks steadily without support", "Begins to run (wobbly)", "Climbs onto low furniture", "Stacks 2–3 blocks"],
    language: ["Speaks 5–20 words", "Responds to simple instructions", "Points to familiar objects", "Babbles with intention"],
    cognitive: ["Recognises herself in mirror", "Simple cause-effect understanding", "Object permanence mastered"],
    socialEmotional: ["Shows affection to parents", "Separation anxiety present", "Imitates adult actions"],
    creative: ["Scribbles with thick crayons", "Responds to music and rhythm", "Simple sensory exploration"],
  },
  {
    id: "m18",
    age: "18 months",
    month: 18,
    physical: ["Walks up stairs holding hand", "Uses spoon (messily)", "Kicks ball forward", "Squats to pick up objects"],
    language: ["10+ clear words", "Tries to repeat new words", "Identifies body parts", "Understands 50+ words"],
    cognitive: ["Simple 2-piece puzzles", "Identifies objects in pictures", "Begins to sort by shape"],
    socialEmotional: ["Engages in early pretend play", "Hands you a book to read", "Notices when others are sad"],
    creative: ["Scribbles spontaneously", "Finger paints", "Begins to imitate drawing"],
  },
  {
    id: "m20",
    age: "20 months",
    month: 20,
    physical: ["Runs stiffly", "Throws ball overhand", "Jumps with both feet (attempts)", "Imitates household chores"],
    language: ["20+ words", "Names pictures in a book", "Uses gestures with words", "Vocabulary growing rapidly"],
    cognitive: ["Follows 2-step instruction", "Stacks 5–6 blocks", "Names 1–2 colours", "Categorises objects"],
    socialEmotional: ["Parallel play near other children", "Shows pride in accomplishments", "Expresses a wide range of emotions"],
    creative: ["Explores with play dough", "Begins pretend play sequences", "Music with movement"],
  },
  {
    id: "m22",
    age: "22 months",
    month: 22,
    physical: ["Runs confidently", "Kicks ball while walking", "Climbs playground equipment", "Washes hands with help"],
    language: ["Uses 2-word phrases ('More milk')", "Refers to self by name", "Asks 'what' questions", "Building vocabulary rapidly"],
    cognitive: ["Pretend play sequences", "Sorts by colour", "Remembers where objects go", "Completes 3–4 piece puzzles"],
    socialEmotional: ["Notices when others are upset", "Expresses feelings in words (early)", "Turn-taking beginning"],
    creative: ["Finger painting with intention", "Sings fragments of songs", "Play dough sculpting"],
  },
  {
    id: "m24",
    age: "24 months",
    month: 24,
    physical: ["Runs and kicks confidently", "Jumps with both feet", "Walks up stairs independently", "Uses spoon and fork well"],
    language: ["50+ words", "2-word sentences consistently", "Asks 'where' questions", "Strangers understand ~50% of speech"],
    cognitive: ["Symbolic play developed", "Basic problem-solving", "Counts to 3 with help", "Memory for recent events"],
    socialEmotional: ["Begins to show empathy", "Simple turn-taking games", "Expresses emotions with words"],
    creative: ["Draws circles intentionally", "Sings simple songs", "Imaginative play sequences begin"],
  },
  {
    id: "m26",
    age: "26 months",
    month: 26,
    physical: ["Runs, jumps, climbs", "Kicks and throws with aim", "Begins pedalling", "Draws simple shapes"],
    language: ["75+ words", "2–3 word sentences", "Asks many questions", "Tells short stories about events"],
    cognitive: ["Matches animal to habitat", "Counts objects to 3", "Understands yesterday/today", "Categorises animals, vehicles, food"],
    socialEmotional: ["Shows genuine empathy", "Understands sharing (though difficult)", "Parallel to early cooperative play"],
    creative: ["Imaginative play with narratives", "Draws people as circles with lines", "Recognises 4–6 colours"],
  },
  {
    id: "m28",
    age: "28 months",
    month: 28,
    physical: ["Runs confidently, changes direction", "Hops on one foot (attempts)", "Uses scissors with help", "Partially dresses herself"],
    language: ["100+ words, 3-word sentences", "Strangers understand most speech", "Asks 'why' questions", "Tells simple stories"],
    cognitive: ["Symbolic play, imaginative stories", "Sorts by multiple attributes", "Follows complex 3-step instructions", "Early reading readiness"],
    socialEmotional: ["Genuine empathy and caring", "Cooperative play beginning", "Expresses preferences confidently"],
    creative: ["Draw with intention and explanation", "Sings full songs", "Inventive imaginative play"],
  },
];

export const NUTRITION = [
  { time: "7:00 AM", meal: "Wake-up", options: ["150ml warm milk (cow or buffalo)"], focus: "Hydration & gentle start" },
  { time: "8:00 AM", meal: "Breakfast", options: ["Suji upma", "Moong dal cheela", "Ragi porridge", "Poha", "Soft idli with sambar"], focus: "Iron & complex carbohydrates" },
  { time: "10:30 AM", meal: "Mid-Morning Snack", options: ["Banana", "Chikoo", "Mango slice", "Curd with honey (after 1 year)"], focus: "Natural sugars & probiotics" },
  { time: "12:30 PM", meal: "Lunch", options: ["Dal khichdi with ghee", "Rice + dal + mashed sabzi", "Paneer paratha with curd", "Soft roti with dal"], focus: "Protein & brain fats (ghee)" },
  { time: "3:00 PM", meal: "Afternoon Snack", options: ["Dhokla", "Boiled sweet potato", "Roasted makhana", "Banana with peanut butter"], focus: "Sustained energy" },
  { time: "5:00 PM", meal: "Evening Snack", options: ["Whole wheat crackers", "Steamed corn", "Coconut water", "Fruit slices"], focus: "Minerals & hydration" },
  { time: "7:30 PM", meal: "Dinner", options: ["Soft roti with dal", "Veg khichdi", "Light bottle gourd sabzi", "Soft idli"], focus: "Easy digestion for deep sleep" },
];

export const BRAIN_FOODS = [
  { nutrient: "Iron", benefit: "Cognitive function & focus", sources: ["Ragi", "Rajma", "Palak", "Jaggery (Gud)", "Pomegranate", "Dates"] },
  { nutrient: "Omega-3", benefit: "Brain cell membrane health", sources: ["Walnuts", "Flaxseeds (Alsi)", "Fish (if non-veg)"] },
  { nutrient: "Probiotics", benefit: "Gut-brain axis health", sources: ["Homemade dahi (curd)", "Idli batter", "Kanji"] },
  { nutrient: "Brain Fats", benefit: "Neural development", sources: ["Ghee (1–2 tsp daily)", "Coconut", "Avocado"] },
  { nutrient: "Calcium", benefit: "Neural transmission", sources: ["Ragi", "Paneer", "Dahi", "Sesame seeds (til)"] },
  { nutrient: "Zinc", benefit: "Immune & cognitive function", sources: ["Pumpkin seeds", "Dal", "Whole grains"] },
];

export const DAILY_RHYTHM = [
  { time: "6:30 AM", activity: "Wake & Morning Sunlight", pillars: ["physical"] as Pillar[], note: "Natural light sets the circadian rhythm — open curtains before screens" },
  { time: "7:30 AM", activity: "Breakfast with Self-Feeding", pillars: ["physical", "cognitive"] as Pillar[], note: "Let her spoon herself, however messily. Autonomy is the lesson." },
  { time: "9:00 AM", activity: "Outdoor Exploration", pillars: ["physical", "cognitive"] as Pillar[], note: "The best developmental window of the day. Park, garden, or terrace." },
  { time: "11:00 AM", activity: "Sensory or Creative Lab", pillars: ["creative", "cognitive"] as Pillar[], note: "Atta dough, water play, or process painting." },
  { time: "12:30 PM", activity: "Lunch & Wind Down", pillars: ["physical"] as Pillar[], note: "Begin quieting stimulation 30 minutes before nap." },
  { time: "1:00 PM", activity: "Sacred Nap", pillars: ["cognitive"] as Pillar[], note: "Non-negotiable. Growth hormones release exclusively during sleep." },
  { time: "4:00 PM", activity: "Household Helper", pillars: ["cognitive", "socialEmotional"] as Pillar[], note: "Maximum effort tasks: laundry basket, wiping, carrying." },
  { time: "6:00 PM", activity: "Bath Time Play", pillars: ["cognitive", "creative"] as Pillar[], note: "Pouring, floating, and volume play." },
  { time: "7:00 PM", activity: "Books & Storytelling", pillars: ["language", "socialEmotional"] as Pillar[], note: "Read 2–3 books. Point and wait 5 seconds for her to name." },
  { time: "7:30 PM", activity: "Lullabies & Sleep", pillars: ["socialEmotional"] as Pillar[], note: "Your voice is her safe harbour. Chanda Mama, Lakdi ki Kathi." },
];

export const PILLAR_COLORS: Record<Pillar, string> = {
  cognitive: "cognitive",
  language: "language",
  physical: "physical",
  socialEmotional: "socialEmotional",
  creative: "creative",
};

export const PILLAR_LABELS: Record<Pillar, string> = {
  cognitive: "Cognitive",
  language: "Language",
  physical: "Physical",
  socialEmotional: "Social-Emotional",
  creative: "Creative",
};

export const PILLAR_ICONS: Record<Pillar, string> = {
  cognitive: "brain",
  language: "chat-bubble-left",
  physical: "bolt",
  socialEmotional: "heart",
  creative: "paint-brush",
};

export const CATEGORY_LABELS: Record<string, string> = {
  sensory: "Sensory",
  motor: "Motor",
  language: "Language",
  creative: "Creative",
  cognitive: "Cognitive",
  outdoor: "Outdoor",
};
